homeassistant:
  name: My Smart Home
  latitude: !secret latitude_coord
  longitude: !secret longitude_coord
  elevation: 179
  unit_system: metric
  time_zone: Europe/Kiev
  customize: !include customize.yaml
  packages: !include_dir_merge_named includes/packages


# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:
    
frontend:
  themes: !include_dir_merge_named themes

# Uncomment this if you are using SSL/TLS, running in Docker container, etc.
# http:
#   base_url: example.duckdns.org:8123

lovelace:
  mode: yaml
  resources:
   - url: /hacsfiles/mini-graph-card/mini-graph-card-bundle.js
     type: module  

# Text to speech
tts:
  - platform: google_translate
  
# mqtt:
#   broker: core-mosquitto  # Локальный брокер
#   broker: 192.168.0.70   # Внешний брокер
#   discovery: true
#   discovery_prefix: homeassistant  
#   username: mqtt
#   password: mqtt

#Вынос во внешние файлы
timer: !include includes/timer.yaml
input_select: !include includes/input_select.yaml
input_boolean: !include includes/input_boolean.yaml
group: !include includes/groups.yaml
scene: !include includes/scenes.yaml
recorder: !include includes/recorder.yaml
# yeelight: !include includes/yeelight.yaml
light: !include includes/light.yaml
fan: !include includes/fan.yaml
air_quality: !include includes/air_quality.yaml
remote: !include includes/remote.yaml
#mqtt_statestream: !include includes/mqtt_statestream.yaml

#Вынос во внешние папки
sensor: !include_dir_merge_list includes/sensor
automation: !include_dir_merge_list includes/automation
switch: !include_dir_merge_list includes/switches
script: !include_dir_merge_named includes/scripts
binary_sensor: !include_dir_merge_list includes/bin_sensor


telegram_bot:
  - platform: polling
    api_key: !secret api_key_bot
    allowed_chat_ids:
     - !secret telegram_id_1
     - !secret telegram_id_2    
      
notify:

  - name: telegram_id_1
    platform: telegram
    chat_id: !secret telegram_id_1
    
  - name: telegram_id_2
    platform: telegram
    chat_id: !secret telegram_id_2